# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: cursus

steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'dennisvermeulen-devops'
    subscriptionId: 'c3deb1e1-7a98-406d-832c-64df188877df'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-dennisvermeulen-devops'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/DennisVermeulen/aks-pipeline-deployment/main/azuredeploy.json?token=ACWUXS4KFF6LF3OK73FMTFTBT3AOS'
    deploymentMode: 'Complete'