# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: cursus

stages:
  - stage: Create_AKS_Cluster
    displayName: create AKS cluster
    jobs:
    - job: create_aks_cluster
      steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'dennisvermeulen-devops'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az group deployment create \
              --mode Incremental \
              --resource-group "rg-dennisvermeulen-devops" \
              --subscription $(SUBSCRIPTION) \
              --template-file "azuredeploy.json" \
              --parameters \
                dnsPrefix="aks-eus2-aksdays-demo-01" \
                agentCount="1" \
                aksClusterName="aks-eus2-aksdays-demo-01" \
                agentVMSize="Standard_B2s"

